name: Pandaswork
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pandas
  - matplotlib
  - jupyter
  - fastapi
  - uvicorn
  - scikit-learn
  - plotly
  - pip
  - pip:
      - streamlit
